### ISSUE TITLE
Printing special characters

### ISSUE THREAD

**Issue by Streifenpferd** [craibuc/PsZebra#2]
I have problems with special characters like ä, ö, ü. Also replacing the special characters with UTF-8 hex code was no solution. Do you have a tip for me?

**Comment by craibuc** [comment]
Are you able to print those characters successfully using another application or their design tool?

What is printed in place of the character with a diacritical mark?

`'^FT78,76^A0N,28,28^FH\^FDIch hänge das Poster an die Wand.^FS' | Out-ZebraPrinter -IpAddress 10.10.10.10 -Port 9100`

**Comment by craibuc** [comment]
Maybe change the encoding?  [Write Unicode String In a File Using StreamWriter doesn't Work](https://stackoverflow.com/questions/8196760/write-unicode-string-in-a-file-using-streamwriter-doesnt-work).

Change this line: https://github.com/craibuc/PsZebra/blob/d465d6944f3430a146581072c3aeca4739eeff0f/PsZebra/Public/Out-ZebraPrinter.ps1#L43
 
to this:

```powershell
 $writer = [System.IO.StreamWriter]::new($client.GetStream(), $false, [Encoding]::UTF8)
```
Try toggling the last value between `[Encoding]::Default` and `[Encoding]::UTF8`.

If this works, we can add an `$Encoding` parameter to the function to allow it to be explicitly specified.

**Comment by Streifenpferd** [comment]
It was easier in the west and ultimately my fault. I hope I didn't take too much of your time. 
Adding the "Encoding" parameter caused the printer not to respond.
Adding the *CI28* parameter at the beginning of the ZPL code solved my problem.
Here is the working ZPL code (relevant detail row 2):
```
^XA
^CI28
^FT78,76^A0N,28,28^FH\^FDIch hänge das Poster an die Wand.^FS
^XZ
```
See the attached printed results or check [Labelary](http://labelary.com/viewer.html)
![Scan_20221021-2](https://user-images.githubusercontent.com/11905598/197256544-4fc3342e-38f1-415b-9b7b-f4a83df53227.png)

**Comment by craibuc** [comment]
`^CI` = Change International Font/Encoding
`28` = Unicode (UTF-8 encoding) - Unicode Character Set
